### PR TITLE
ignore first parameter on makeTokenString method

### PR DESCRIPTION
**Pull request by appleboy**
cc @StephanDollberg

### CODE REVIEW

**Comment by StephanDollberg** [comment]
Hi @appleboy ,

Thanks for this cleanup PR. Don't know whether I needed this in the past or not. As we might need this again for the jwt-go 3.0 refactoring I will leave this in for now. It's not urgent anyway.

Thanks,
Stephan

**Comment by appleboy** [comment]
@StephanDollberg Thanks for your response. Or we can change https://github.com/StephanDollberg/go-json-rest-middleware-jwt/blob/master/auth_jwt_test.go#L22 to

```
token.Claims["id"] = username
```

If so, I can update this commit.

**Comment by StephanDollberg** [comment]
Yes, that seems actually the right way to do it. Can you check that no other test implicitly relies on the weird way it currently is?

Thanks!

**Comment by appleboy** [comment]
@StephanDollberg I update commit and add `travis` config for testing. Can you enable `travis` service on project settings? Thanks.

``` bash
$ go test
PASS
ok      _/Users/xxxxx/git/go-json-rest-middleware-jwt        0.011s
```

**Comment by StephanDollberg** [comment]
Merged! Nice, thank you very much. Activated travis support.

**Pull request merged**
