### PR TITLE
Confirm signing algorithm received in parsed token matches configured…

### PR DESCRIPTION
**Pull request by boonep**
Confirm signing algorithm received in parsed token matches configured signing algorithm to prevent maliciously signed payload creation: https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/

### CODE REVIEW

**Comment by StephanDollberg** [comment]
Hi @boonep,

thanks for the PR. 

We are not directly affected by this as per the documentation we don't "support" the RSA methods. However, a user could still pass `RS256` and would be affected so I think it's better if we put this in (plus maybe some check or remove the limitation altogether ). Funnily, I was also thinking about adding this today.

I will have a detailed look later, thanks in the meantime.

Cheers,
Stephan

**Comment by boonep** [comment]
No problem.  Thank you!

**Comment by StephanDollberg** [comment]
Merged, very nice work :+1:  

Thanks!

**Comment by boonep** [comment]
Great.  Thanks for your hard work and quick response.  Glad to help out!

_Boone Putney_
_Soleer.com_
512.922.5474

On Fri, May 29, 2015 at 11:26 AM, Stephan Dollberg <notifications@github.com

**Pull request merged**
