### PR TITLE
Add support for public and private keys

### PR DESCRIPTION
**Pull request by johnandersen777**
I added support for public and private keys so that it can use ecdsa and rsa signing and verifying.

Also I renamed it to Middleware because it is already called from other packages as jwt.JWTMiddleware so I didn't see much reason to say JWT twice.

### CODE REVIEW

**Comment by johnandersen777** [comment]
Oh and I made Authenticator return an error so that clients would know why their auth request failed.

**Comment by StephanDollberg** [comment]
Hi @pdxjohnny,

thanks for this PR.

Some general things. First, this PR contains a lot of different stuff. If we want to get this merged please split up the individual parts into single PRs so that we can better analyse the changes. Second, a lot of your changes are breaking changes so we can't just incorporate them. However, jwt-go is currently undergoing some big rewrite for a third release. This would probably also break some stuff and at that point we could talk about integrating that.

Concerning the individual changes:

Renaming to just `Middleware` and changing the interface of the Authenticator function are both subject to the breaking described above. They are as they currently are because they mimic the [basic auth](https://github.com/ant0ine/go-json-rest/blob/master/rest/auth_basic.go) middleware in go-json-rest. I do however like both of these changes so we should keep them in mind.

I am not sure about the key thing. This is a part where I think the most parts will change in the new version of jwt-go.

I like the idea of passing an error to `unauthorized`. Same goes of course for the cleanup of the variable names in the tests.

Thanks again for all this stuff,
Stephan

**Comment by johnandersen777** [comment]
Yes I was thinking about how there's a lot of different parts in this. I'll
make a few PRs and let you choose what you want if any.

Thanks,
John

**Comment by johnandersen777** [comment]
This is way stale so no point in keeping this open.

**Pull request closed without merging**
